const fs=require('node:fs'),Module=require('node:module'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const root=path.resolve(__dirname,'..');process.env.NODE_ENV='test';process.env.TURSO_DATABASE_URL=':memory:';
const origResolve=Module._resolveFilename;Module._resolveFilename=function(name,...args){return origResolve.call(this,name.startsWith('@/')?root+'/'+name.slice(2):name,...args)};Module._extensions['.ts']=(m,file)=>m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
const {accountRequest,passwordHash}=require('../lib/gip/server/accounts.ts');
async function call(action,body,cookie='',extra={}){const request=new Request('https://gip.test/api/account/'+action,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json',origin:'https://gip.test',cookie,...extra},body:body===undefined?undefined:JSON.stringify(body)});const res=await accountRequest(request,action.split('?')[0]);return {status:res.status,cookie:res.headers.get('set-cookie')?.split(';')[0],headers:res.headers,data:action.startsWith('photo')&&res.ok?new Uint8Array(await res.arrayBuffer()):await res.json()}}
(async()=>{
 const created=await call('signup',{nickname:'device A',password:'test-password-123'});assert.equal(created.status,200);assert.match(created.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);const profile=created.data,cookieA=created.cookie;assert.equal('notifications' in profile,false);
 assert.equal((await call('profile',{...profile,teamIds:['kbo-0'],nickname:'same account'},cookieA)).status,200);
 const review={kind:'visit',gameId:null,date:'2026-09-30',matchup:'롯데 vs KIA',venue:'사직야구장',content:'다른 기기에서도 보이는 기록',seat:'1루',photoData:'data:image/png;base64,iVBORw0KGgo=',photoName:'test.png'};
 const saved=await call('review',{review},cookieA);assert.equal(saved.status,200);
 const deviceB=await call('login',{code:profile.gipCode,password:'test-password-123'});assert.equal(deviceB.data.id,profile.id);assert.equal(deviceB.data.nickname,'same account');assert.deepEqual(deviceB.data.teamIds,['kbo-0']);assert.notEqual(deviceB.cookie,cookieA);
 const records=await call('reviews',undefined,deviceB.cookie);assert.equal(records.data[0].content,review.content);assert.equal((await call('photo?id='+saved.data.id,undefined,deviceB.cookie)).status,200);
 assert.equal((await call('login',{code:profile.gipCode,password:'incorrect-password'})).status,401);
 const other=await call('signup',{nickname:'other',password:'another-password'});assert.deepEqual((await call('reviews',undefined,other.cookie)).data,[]);assert.equal((await call('photo?id='+saved.data.id,undefined,other.cookie)).status,404);
 await call('review',{id:saved.data.id,remove:true},other.cookie);assert.equal((await call('reviews',undefined,cookieA)).data.length,1);
 assert.equal((await call('profile',{...profile,nickname:'CSRF'},cookieA,{origin:'https://evil.test'})).status,403);
 await call('logout',{},deviceB.cookie);assert.equal((await call('session',undefined,deviceB.cookie)).data,null);assert.equal((await call('session',undefined,cookieA)).data.id,profile.id);
 const salt='legacy-salt',pw='legacy-password',digest=await passwordHash(pw,salt),legacy=await call('migrate',{code:'ABC123',password:pw,salt,digest,profile:{...profile,nickname:'legacy',notifications:{start:true,final:true}}});assert.equal(legacy.status,200);assert.equal('notifications' in legacy.data,false);assert.equal(legacy.data.nickname,'legacy');const id=crypto.randomUUID();await call('review',{id,review},legacy.cookie);await call('review',{id,review},legacy.cookie);assert.equal((await call('reviews',undefined,legacy.cookie)).data.length,1);assert.equal((await call('login',{code:'ABC123',password:pw})).data.id,legacy.data.id);
 assert.equal((await call('migrate',{code:'ABC123',password:pw,salt,digest,profile})).status,409);
 for(let i=0;i<20;i++)await call('login',{code:'99999',password:'bad-password'},{},{'x-vercel-forwarded-for':'test-limit'});assert.equal((await call('login',{code:'99999',password:'bad-password'},'',{'x-vercel-forwarded-for':'test-limit'})).status,429);
 const db=require('../lib/gip/server/account-store.ts').database();
 const oldAccount=await db.prepare('SELECT profile FROM accounts WHERE id=?').bind(profile.id).first();
 await db.prepare('UPDATE accounts SET profile=? WHERE id=?').bind(JSON.stringify({...JSON.parse(oldAccount.profile),notifications:{start:true,final:false}}),profile.id).run();
 const oldSession=await call('session',undefined,cookieA);assert.equal(oldSession.data.id,profile.id);assert.equal(oldSession.data.nickname,'same account');assert.equal('notifications' in oldSession.data,false);assert.equal((await call('reviews',undefined,cookieA)).data.length,1);
 const oldLogin=await call('login',{code:profile.gipCode,password:'test-password-123'});assert.equal(oldLogin.status,200);assert.equal(oldLogin.data.id,profile.id);assert.equal('notifications' in oldLogin.data,false);
 const updatedOld=await call('profile',{...oldSession.data,nickname:'still same account',notifications:{start:false,final:true}},cookieA);assert.equal(updatedOld.status,200);assert.equal('notifications' in updatedOld.data,false);assert.equal(updatedOld.data.id,profile.id);
 await assert.rejects(db.batch([db.prepare('INSERT INTO photos(key,data,content_type) VALUES(?,?,?)').bind('rollback',new Uint8Array([1]),'image/png'),db.prepare('INSERT INTO photos(key,data,content_type) VALUES(?,?,?)').bind('rollback',new Uint8Array([2]),'image/png')]));assert.equal(await db.prepare('SELECT key FROM photos WHERE key=?').bind('rollback').first(),null);
 console.log('PASS: cross-device login, preferences, reviews/photos, password rejection, ownership, CSRF, independent logout, legacy migration, retired notification compatibility, idempotent import, duplicate codes, login throttling');
})().catch(e=>{console.error(e);process.exitCode=1});
